import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex("master_countries").del();

  // Inserts seed entries
  await knex("master_countries").insert([
    {
      id: 1,
      name: "Afghanistan",
      code: "AF",
      capital: "Kabul",
      region: "AS",
      language: {
        code: "ps",
        name: "Pashto",
      },
      flag: "https://restcountries.eu/data/afg.svg",
      iso_code: "AF",
    },
    {
      id: 2,
      name: "Åland Islands",
      code: "AX",
      capital: "Mariehamn",
      region: "EU",
      language: {
        code: "sv",
        name: "Swedish",
      },
      flag: "https://restcountries.eu/data/ala.svg",
      iso_code: "AX",
    },
    {
      id: 3,
      name: "Albania",
      code: "AL",
      capital: "Tirana",
      region: "EU",
      language: {
        code: "sq",
        name: "Albanian",
      },
      flag: "https://restcountries.eu/data/alb.svg",
      iso_code: "AL",
    },
    {
      id: 4,
      name: "Algeria",
      code: "DZ",
      capital: "Algiers",
      region: "AF",
      language: {
        code: "ar",
        name: "Arabic",
      },
      flag: "https://restcountries.eu/data/dza.svg",
      iso_code: "DZ",
    },
    {
      id: 5,
      name: "American Samoa",
      code: "AS",
      capital: "Pago Pago",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/asm.svg",
      iso_code: "AS",
    },
    {
      id: 6,
      name: "Andorra",
      code: "AD",
      capital: "Andorra la Vella",
      region: "EU",
      language: {
        code: "ca",
        name: "Catalan",
      },
      flag: "https://restcountries.eu/data/and.svg",
      iso_code: "AD",
    },
    {
      id: 7,
      name: "Angola",
      code: "AO",
      capital: "Luanda",
      region: "AF",
      language: {
        code: "pt",
        name: "Portuguese",
      },
      flag: "https://restcountries.eu/data/ago.svg",
      iso_code: "AO",
    },
    {
      id: 8,
      name: "Anguilla",
      code: "AI",
      capital: "The Valley",
      region: "NA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/aia.svg",
      iso_code: "AI",
    },
    {
      id: 9,
      name: "Antigua and Barbuda",
      code: "AG",
      capital: "Saint John's",
      region: "NA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/atg.svg",
      iso_code: "AG",
    },
    {
      id: 10,
      name: "Argentina",
      code: "AR",
      capital: "Buenos Aires",
      region: "SA",
      language: {
        code: "es",
        name: "Spanish",
      },
      flag: "https://restcountries.eu/data/arg.svg",
      iso_code: "AR",
    },
    {
      id: 11,
      name: "Armenia",
      code: "AM",
      capital: "Yerevan",
      region: "AS",
      language: {
        code: "hy",
        name: "Armenian",
      },
      flag: "https://restcountries.eu/data/arm.svg",
      iso_code: "AM",
    },
    {
      id: 12,
      name: "Aruba",
      code: "AW",
      capital: "Oranjestad",
      region: "SA",
      language: {
        code: "nl",
        name: "Dutch",
      },
      flag: "https://restcountries.eu/data/abw.svg",
      iso_code: "AW",
    },
    {
      id: 13,
      name: "Australia",
      code: "AU",
      capital: "Canberra",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/aus.svg",
      iso_code: "AU",
    },
    {
      id: 14,
      name: "Austria",
      code: "AT",
      capital: "Vienna",
      region: "EU",
      language: {
        code: "de",
        name: "German",
      },
      flag: "https://restcountries.eu/data/aut.svg",
      iso_code: "AT",
    },
    {
      id: 15,
      name: "Azerbaijan",
      code: "AZ",
      capital: "Baku",
      region: "AS",
      language: {
        code: "az",
        name: "Azerbaijani",
      },
      flag: "https://restcountries.eu/data/aze.svg",
      iso_code: "AZ",
    },
    {
      id: 16,
      name: "Bahamas",
      code: "BS",
      capital: "Nassau",
      region: "NA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/bhs.svg",
      iso_code: "BS",
    },
    {
      id: 17,
      name: "Bahrain",
      code: "BH",
      capital: "Manama",
      region: "AS",
      language: {
        code: "ar",
        name: "Arabic",
      },
      flag: "https://restcountries.eu/data/bhr.svg",
      iso_code: "BH",
    },
    {
      id: 18,
      name: "Bangladesh",
      code: "BD",
      capital: "Dhaka",
      region: "AS",
      language: {
        code: "bn",
        name: "Bengali",
      },
      flag: "https://restcountries.eu/data/bgd.svg",
      iso_code: "BD",
    },
    {
      id: 19,
      name: "Barbados",
      code: "BB",
      capital: "Bridgetown",
      region: "NA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/brb.svg",
      iso_code: "BB",
    },
    {
      id: 20,
      name: "Belarus",
      code: "BY",
      capital: "Minsk",
      region: "EU",
      language: {
        code: "be",
        name: "Belarusian",
      },
      flag: "https://restcountries.eu/data/blr.svg",
      iso_code: "BY",
    },
    {
      id: 21,
      name: "Belgium",
      code: "BE",
      capital: "Brussels",
      region: "EU",
      language: {
        code: "nl",
        name: "Dutch",
      },
      flag: "https://restcountries.eu/data/bel.svg",
      iso_code: "BE",
    },
    {
      id: 22,
      name: "Belize",
      code: "BZ",
      capital: "Belmopan",
      region: "NA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/blz.svg",
      iso_code: "BZ",
    },
    {
      id: 23,
      name: "Benin",
      code: "BJ",
      capital: "Porto-Novo",
      region: "AF",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/ben.svg",
      iso_code: "BJ",
    },
    {
      id: 24,
      name: "Bermuda",
      code: "BM",
      capital: "Hamilton",
      region: "NA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/bmu.svg",
      iso_code: "BM",
    },
    {
      id: 25,
      name: "Bhutan",
      code: "BT",
      capital: "Thimphu",
      region: "AS",
      language: {
        code: "dz",
        name: "Dzongkha",
      },
      flag: "https://restcountries.eu/data/btn.svg",
      iso_code: "BT",
    },
    {
      id: 26,
      name: "Bolivia (Plurinational State of)",
      code: "BO",
      capital: "Sucre",
      region: "SA",
      language: {
        code: "es",
        name: "Spanish",
      },
      flag: "https://restcountries.eu/data/bol.svg",
      iso_code: "BO",
    },
    {
      id: 27,
      name: "Bonaire, Sint Eustatius and Saba",
      code: "BQ",
      capital: "Kralendijk",
      region: "SA",
      language: {
        code: "nl",
        name: "Dutch",
      },
      flag: "https://restcountries.eu/data/bes.svg",
      iso_code: "BQ",
    },
    {
      id: 28,
      name: "Bosnia and Herzegovina",
      code: "BA",
      capital: "Sarajevo",
      region: "EU",
      language: {
        code: "bs",
        name: "Bosnian",
      },
      flag: "https://restcountries.eu/data/bih.svg",
      iso_code: "BA",
    },
    {
      id: 29,
      name: "Botswana",
      code: "BW",
      capital: "Gaborone",
      region: "AF",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/bwa.svg",
      iso_code: "BW",
    },
    {
      id: 30,
      name: "Bouvet Island",
      code: "BV",
      capital: "",
      region: "AN",
      language: {
        code: "no",
        name: "Norwegian",
      },
      flag: "https://restcountries.eu/data/bvt.svg",
      iso_code: "BV",
    },
    {
      id: 31,
      name: "Brazil",
      code: "BR",
      capital: "Brasília",
      region: "SA",
      language: {
        code: "pt",
        name: "Portuguese",
      },
      flag: "https://restcountries.eu/data/bra.svg",
      iso_code: "BR",
    },
    {
      id: 32,
      name: "British Indian Ocean Territory",
      code: "IO",
      capital: "Diego Garcia",
      region: "AF",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/iot.svg",
      iso_code: "IO",
    },
    {
      id: 33,
      name: "United States Minor Outlying Islands",
      code: "UM",
      capital: "",
      region: "NA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/umi.svg",
      iso_code: "UM",
    },
    {
      id: 34,
      name: "Virgin Islands (British)",
      code: "VG",
      capital: "Road Town",
      region: "NA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/vgb.svg",
      iso_code: "VG",
    },
    {
      id: 35,
      name: "Virgin Islands (U.S.)",
      code: "VI",
      capital: "Charlotte Amalie",
      region: "NA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/vir.svg",
      iso_code: "VI",
    },
    {
      id: 36,
      name: "Brunei Darussalam",
      code: "BN",
      capital: "Bandar Seri Begawan",
      region: "AS",
      language: {
        code: "ms",
        name: "Malay",
      },
      flag: "https://restcountries.eu/data/brn.svg",
      iso_code: "BN",
    },
    {
      id: 37,
      name: "Bulgaria",
      code: "BG",
      capital: "Sofia",
      region: "EU",
      language: {
        code: "bg",
        name: "Bulgarian",
      },
      flag: "https://restcountries.eu/data/bgr.svg",
      iso_code: "BG",
    },
    {
      id: 38,
      name: "Burkina Faso",
      code: "BF",
      capital: "Ouagadougou",
      region: "AF",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/bfa.svg",
      iso_code: "BF",
    },
    {
      id: 39,
      name: "Burundi",
      code: "BI",
      capital: "Bujumbura",
      region: "AF",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/bdi.svg",
      iso_code: "BI",
    },
    {
      id: 40,
      name: "Cambodia",
      code: "KH",
      capital: "Phnom Penh",
      region: "AS",
      language: {
        code: "km",
        name: "Khmer",
      },
      flag: "https://restcountries.eu/data/khm.svg",
      iso_code: "KH",
    },
    {
      id: 41,
      name: "Cameroon",
      code: "CM",
      capital: "Yaoundé",
      region: "AF",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/cmr.svg",
      iso_code: "CM",
    },
    {
      id: 42,
      name: "Canada",
      code: "CA",
      capital: "Ottawa",
      region: "NA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/can.svg",
      iso_code: "CA",
    },
    {
      id: 43,
      name: "Cabo Verde",
      code: "CV",
      capital: "Praia",
      region: "AF",
      language: {
        code: "pt",
        iso639_2: "por",
        name: "Portuguese",
        nativeName: "Português",
      },
      flag: "https://restcountries.eu/data/cpv.svg",
      iso_code: "CV",
    },
    {
      id: 44,
      name: "Cayman Islands",
      code: "KY",
      capital: "George Town",
      region: "NA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/cym.svg",
      iso_code: "KY",
    },
    {
      id: 45,
      name: "Central African Republic",
      code: "CF",
      capital: "Bangui",
      region: "AF",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/caf.svg",
      iso_code: "CF",
    },
    {
      id: 46,
      name: "Chad",
      code: "TD",
      capital: "N'Djamena",
      region: "AF",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/tcd.svg",
      iso_code: "TD",
    },
    {
      id: 47,
      name: "Chile",
      code: "CL",
      capital: "Santiago",
      region: "SA",
      language: {
        code: "es",
        iso639_2: "spa",
        name: "Spanish",
        nativeName: "Español",
      },
      flag: "https://restcountries.eu/data/chl.svg",
      iso_code: "CL",
    },
    {
      id: 48,
      name: "China",
      code: "CN",
      capital: "Beijing",
      region: "AS",
      language: {
        code: "zh",
        name: "Chinese",
      },
      flag: "https://restcountries.eu/data/chn.svg",
      iso_code: "CN",
    },
    {
      id: 49,
      name: "Christmas Island",
      code: "CX",
      capital: "Flying Fish Cove",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/cxr.svg",
      iso_code: "CX",
    },
    {
      id: 50,
      name: "Cocos (Keeling) Islands",
      code: "CC",
      capital: "West Island",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/cck.svg",
      iso_code: "CC",
    },
    {
      id: 51,
      name: "Colombia",
      code: "CO",
      capital: "Bogotá",
      region: "SA",
      language: {
        code: "es",
        name: "Spanish",
      },
      flag: "https://restcountries.eu/data/col.svg",
      iso_code: "CO",
    },
    {
      id: 52,
      name: "Comoros",
      code: "KM",
      capital: "Moroni",
      region: "AF",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/com.svg",
      iso_code: "KM",
    },
    {
      id: 53,
      name: "Congo",
      code: "CG",
      capital: "Brazzaville",
      region: "AF",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/cog.svg",
      iso_code: "CG",
    },
    {
      id: 54,
      name: "Congo (Democratic Republic of the)",
      code: "CD",
      capital: "Kinshasa",
      region: "AF",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/cod.svg",
      iso_code: "CD",
    },
    {
      id: 55,
      name: "Cook Islands",
      code: "CK",
      capital: "Avarua",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/cok.svg",
      iso_code: "CK",
    },
    {
      id: 56,
      name: "Costa Rica",
      code: "CR",
      capital: "San José",
      region: "NA",
      language: {
        code: "es",
        name: "Spanish",
      },
      flag: "https://restcountries.eu/data/cri.svg",
      iso_code: "CR",
    },
    {
      id: 57,
      name: "Croatia",
      code: "HR",
      capital: "Zagreb",
      region: "EU",
      language: {
        code: "hr",
        name: "Croatian",
      },
      flag: "https://restcountries.eu/data/hrv.svg",
      iso_code: "HR",
    },
    {
      id: 58,
      name: "Cuba",
      code: "CU",
      capital: "Havana",
      region: "NA",
      language: {
        code: "es",
        name: "Spanish",
      },
      flag: "https://restcountries.eu/data/cub.svg",
      iso_code: "CU",
    },
    {
      id: 59,
      name: "Curaçao",
      code: "CW",
      capital: "Willemstad",
      region: "SA",
      language: {
        code: "nl",
        name: "Dutch",
      },
      flag: "https://restcountries.eu/data/cuw.svg",
      iso_code: "CW",
    },
    {
      id: 60,
      name: "Cyprus",
      code: "CY",
      capital: "Nicosia",
      region: "EU",
      language: {
        code: "tr",
        name: "Turkish",
      },
      flag: "https://restcountries.eu/data/cyp.svg",
      iso_code: "CY",
    },
    {
      id: 61,
      name: "Czech Republic",
      code: "CZ",
      capital: "Prague",
      region: "EU",
      language: {
        code: "cs",
        name: "Czech",
      },
      flag: "https://restcountries.eu/data/cze.svg",
      iso_code: "CZ",
    },
    {
      id: 62,
      name: "Denmark",
      code: "DK",
      capital: "Copenhagen",
      region: "EU",
      language: {
        code: "da",
        name: "Danish",
      },
      flag: "https://restcountries.eu/data/dnk.svg",
      iso_code: "DK",
    },
    {
      id: 63,
      name: "Djibouti",
      code: "DJ",
      capital: "Djibouti",
      region: "AF",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/dji.svg",
      iso_code: "DJ",
    },
    {
      id: 64,
      name: "Dominica",
      code: "DM",
      capital: "Roseau",
      region: "NA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/dma.svg",
      iso_code: "DM",
    },
    {
      id: 65,
      name: "Dominican Republic",
      code: "DO",
      capital: "Santo Domingo",
      region: "NA",
      language: {
        code: "es",
        name: "Spanish",
      },
      flag: "https://restcountries.eu/data/dom.svg",
      iso_code: "DO",
    },
    {
      id: 66,
      name: "Ecuador",
      code: "EC",
      capital: "Quito",
      region: "SA",
      language: {
        code: "es",
        name: "Spanish",
      },
      flag: "https://restcountries.eu/data/ecu.svg",
      iso_code: "EC",
    },
    {
      id: 67,
      name: "Egypt",
      code: "EG",
      capital: "Cairo",
      region: "AF",
      language: {
        code: "ar",
        name: "Arabic",
      },
      flag: "https://restcountries.eu/data/egy.svg",
      iso_code: "EG",
    },
    {
      id: 68,
      name: "El Salvador",
      code: "SV",
      capital: "San Salvador",
      region: "NA",
      language: {
        code: "es",
        name: "Spanish",
      },
      flag: "https://restcountries.eu/data/slv.svg",
      iso_code: "SV",
    },
    {
      id: 69,
      name: "Equatorial Guinea",
      code: "GQ",
      capital: "Malabo",
      region: "AF",
      language: {
        code: "es",
        iso639_2: "spa",
        name: "Spanish",
        nativeName: "Español",
      },
      flag: "https://restcountries.eu/data/gnq.svg",
      iso_code: "GQ",
    },
    {
      id: 70,
      name: "Eritrea",
      code: "ER",
      capital: "Asmara",
      region: "AF",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/eri.svg",
      iso_code: "ER",
    },
    {
      id: 71,
      name: "Estonia",
      code: "EE",
      capital: "Tallinn",
      region: "EU",
      language: {
        code: "et",
        name: "Estonian",
      },
      flag: "https://restcountries.eu/data/est.svg",
      iso_code: "EE",
    },
    {
      id: 72,
      name: "Ethiopia",
      code: "ET",
      capital: "Addis Ababa",
      region: "AF",
      language: {
        code: "am",
        name: "Amharic",
      },
      flag: "https://restcountries.eu/data/eth.svg",
      iso_code: "ET",
    },
    {
      id: 73,
      name: "Falkland Islands (Malvinas)",
      code: "FK",
      capital: "Stanley",
      region: "SA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/flk.svg",
      iso_code: "FK",
    },
    {
      id: 74,
      name: "Faroe Islands",
      code: "FO",
      capital: "Tórshavn",
      region: "EU",
      language: {
        code: "fo",
        name: "Faroese",
      },
      flag: "https://restcountries.eu/data/fro.svg",
      iso_code: "FO",
    },
    {
      id: 75,
      name: "Fiji",
      code: "FJ",
      capital: "Suva",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/fji.svg",
      iso_code: "FJ",
    },
    {
      id: 76,
      name: "Finland",
      code: "FI",
      capital: "Helsinki",
      region: "EU",
      language: {
        code: "fi",
        iso639_2: "fin",
        name: "Finnish",
        nativeName: "suomi",
      },
      flag: "https://restcountries.eu/data/fin.svg",
      iso_code: "FI",
    },
    {
      id: 77,
      name: "France",
      code: "FR",
      capital: "Paris",
      region: "EU",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/fra.svg",
      iso_code: "FR",
    },
    {
      id: 78,
      name: "French Guiana",
      code: "GF",
      capital: "Cayenne",
      region: "SA",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/guf.svg",
      iso_code: "GF",
    },
    {
      id: 79,
      name: "French Polynesia",
      code: "PF",
      capital: "Papeetē",
      region: "OC",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/pyf.svg",
      iso_code: "PF",
    },
    {
      id: 80,
      name: "French Southern Territories",
      code: "TF",
      capital: "Port-aux-Français",
      region: "AF",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/atf.svg",
      iso_code: "TF",
    },
    {
      id: 81,
      name: "Gabon",
      code: "GA",
      capital: "Libreville",
      region: "AF",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/gab.svg",
      iso_code: "GA",
    },
    {
      id: 82,
      name: "Gambia",
      code: "GM",
      capital: "Banjul",
      region: "AF",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/gmb.svg",
      iso_code: "GM",
    },
    {
      id: 83,
      name: "Georgia",
      code: "GE",
      capital: "Tbilisi",
      region: "AS",
      language: {
        code: "ka",
        name: "Georgian",
      },
      flag: "https://restcountries.eu/data/geo.svg",
      iso_code: "GE",
    },
    {
      id: 84,
      name: "Germany",
      code: "DE",
      capital: "Berlin",
      region: "EU",
      language: {
        code: "de",
        name: "German",
      },
      flag: "https://restcountries.eu/data/deu.svg",
      iso_code: "DE",
    },
    {
      id: 85,
      name: "Ghana",
      code: "GH",
      capital: "Accra",
      region: "AF",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/gha.svg",
      iso_code: "GH",
    },
    {
      id: 86,
      name: "Gibraltar",
      code: "GI",
      capital: "Gibraltar",
      region: "EU",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/gib.svg",
      iso_code: "GI",
    },
    {
      id: 87,
      name: "Greece",
      code: "GR",
      capital: "Athens",
      region: "EU",
      language: {
        code: "el",
        name: "Greek (modern)",
      },
      flag: "https://restcountries.eu/data/grc.svg",
      iso_code: "GR",
    },
    {
      id: 88,
      name: "Greenland",
      code: "GL",
      capital: "Nuuk",
      region: "NA",
      language: {
        code: "kl",
        name: "Kalaallisut",
      },
      flag: "https://restcountries.eu/data/grl.svg",
      iso_code: "GL",
    },
    {
      id: 89,
      name: "Grenada",
      code: "GD",
      capital: "St. George's",
      region: "NA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/grd.svg",
      iso_code: "GD",
    },
    {
      id: 90,
      name: "Guadeloupe",
      code: "GP",
      capital: "Basse-Terre",
      region: "NA",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/glp.svg",
      iso_code: "GP",
    },
    {
      id: 91,
      name: "Guam",
      code: "GU",
      capital: "Hagåtña",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/gum.svg",
      iso_code: "GU",
    },
    {
      id: 92,
      name: "Guatemala",
      code: "GT",
      capital: "Guatemala City",
      region: "NA",
      language: {
        code: "es",
        name: "Spanish",
      },
      flag: "https://restcountries.eu/data/gtm.svg",
      iso_code: "GT",
    },
    {
      id: 93,
      name: "Guernsey",
      code: "GG",
      capital: "St. Peter Port",
      region: "EU",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/ggy.svg",
      iso_code: "GG",
    },
    {
      id: 94,
      name: "Guinea",
      code: "GN",
      capital: "Conakry",
      region: "AF",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/gin.svg",
      iso_code: "GN",
    },
    {
      id: 95,
      name: "Guinea-Bissau",
      code: "GW",
      capital: "Bissau",
      region: "AF",
      language: {
        code: "pt",
        name: "Portuguese",
      },
      flag: "https://restcountries.eu/data/gnb.svg",
      iso_code: "GW",
    },
    {
      id: 96,
      name: "Guyana",
      code: "GY",
      capital: "Georgetown",
      region: "SA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/guy.svg",
      iso_code: "GY",
    },
    {
      id: 97,
      name: "Haiti",
      code: "HT",
      capital: "Port-au-Prince",
      region: "Americas",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/hti.svg",
      iso_code: "HT",
    },
    {
      id: 98,
      name: "Heard Island and McDonald Islands",
      code: "HM",
      capital: "",
      region: "",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/hmd.svg",
      iso_code: "HM",
    },
    {
      id: 99,
      name: "Holy See",
      code: "VA",
      capital: "Rome",
      region: "EU",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/vat.svg",
      iso_code: "VA",
    },
    {
      id: 100,
      name: "Honduras",
      code: "HN",
      capital: "Tegucigalpa",
      region: "NA",
      language: {
        code: "es",
        name: "Spanish",
      },
      flag: "https://restcountries.eu/data/hnd.svg",
      iso_code: "HN",
    },
    {
      id: 101,
      name: "Hong Kong",
      code: "HK",
      capital: "City of Victoria",
      region: "AS",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/hkg.svg",
      iso_code: "HK",
    },
    {
      id: 102,
      name: "Hungary",
      code: "HU",
      capital: "Budapest",
      region: "EU",
      language: {
        code: "hu",
        name: "Hungarian",
      },
      flag: "https://restcountries.eu/data/hun.svg",
      iso_code: "HU",
    },
    {
      id: 103,
      name: "Iceland",
      code: "IS",
      capital: "Reykjavík",
      region: "EU",
      language: {
        code: "is",
        name: "Icelandic",
      },
      flag: "https://restcountries.eu/data/isl.svg",
      iso_code: "IS",
    },
    {
      id: 104,
      name: "India",
      code: "IN",
      capital: "New Delhi",
      region: "AS",
      language: {
        code: "hi",
        name: "Hindi",
      },
      flag: "https://restcountries.eu/data/ind.svg",
      iso_code: "IN",
    },
    {
      id: 105,
      name: "Indonesia",
      code: "ID",
      capital: "Jakarta",
      region: "AS",
      language: {
        code: "id",
        name: "Indonesian",
      },
      flag: "https://restcountries.eu/data/idn.svg",
      iso_code: "ID",
    },
    {
      id: 106,
      name: "Côte d'Ivoire",
      code: "CI",
      capital: "Yamoussoukro",
      region: "AF",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/civ.svg",
      iso_code: "CI",
    },
    {
      id: 107,
      name: "Iran (Islamic Republic of)",
      code: "IR",
      capital: "Tehran",
      region: "AS",
      language: {
        code: "fa",
        name: "Persian (Farsi)",
      },
      flag: "https://restcountries.eu/data/irn.svg",
      iso_code: "IR",
    },
    {
      id: 108,
      name: "Iraq",
      code: "IQ",
      capital: "Baghdad",
      region: "AS",
      language: {
        code: "ar",
        name: "Arabic",
      },
      flag: "https://restcountries.eu/data/irq.svg",
      iso_code: "IQ",
    },
    {
      id: 109,
      name: "Ireland",
      code: "IE",
      capital: "Dublin",
      region: "EU",
      language: {
        code: "ga",
        name: "Irish",
      },
      flag: "https://restcountries.eu/data/irl.svg",
      iso_code: "IE",
    },
    {
      id: 110,
      name: "Isle of Man",
      code: "IM",
      capital: "Douglas",
      region: "EU",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/imn.svg",
      iso_code: "IM",
    },
    {
      id: 111,
      name: "Israel",
      code: "IL",
      capital: "Jerusalem",
      region: "AS",
      language: {
        code: "he",
        name: "Hebrew (modern)",
      },
      flag: "https://restcountries.eu/data/isr.svg",
      iso_code: "IL",
    },
    {
      id: 112,
      name: "Italy",
      code: "IT",
      capital: "Rome",
      region: "EU",
      language: {
        code: "it",
        name: "Italian",
      },
      flag: "https://restcountries.eu/data/ita.svg",
      iso_code: "IT",
    },
    {
      id: 113,
      name: "Jamaica",
      code: "JM",
      capital: "Kingston",
      region: "NA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/jam.svg",
      iso_code: "JM",
    },
    {
      id: 114,
      name: "Japan",
      code: "JP",
      capital: "Tokyo",
      region: "AS",
      language: {
        code: "ja",
        name: "Japanese",
      },
      flag: "https://restcountries.eu/data/jpn.svg",
      iso_code: "JP",
    },
    {
      id: 115,
      name: "Jersey",
      code: "JE",
      capital: "Saint Helier",
      region: "EU",
      language: {
        code: "en",
        iso639_2: "eng",
        name: "English",
        nativeName: "English",
      },
      flag: "https://restcountries.eu/data/jey.svg",
      iso_code: "JE",
    },
    {
      id: 116,
      name: "Jordan",
      code: "JO",
      capital: "Amman",
      region: "AS",
      language: {
        code: "ar",
        name: "Arabic",
      },
      flag: "https://restcountries.eu/data/jor.svg",
      iso_code: "JO",
    },
    {
      id: 117,
      name: "Kazakhstan",
      code: "KZ",
      capital: "Astana",
      region: "AS",
      language: {
        code: "kk",
        name: "Kazakh",
      },
      flag: "https://restcountries.eu/data/kaz.svg",
      iso_code: "KZ",
    },
    {
      id: 118,
      name: "Kenya",
      code: "KE",
      capital: "Nairobi",
      region: "AF",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/ken.svg",
      iso_code: "KE",
    },
    {
      id: 119,
      name: "Kiribati",
      code: "KI",
      capital: "South Tarawa",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/kir.svg",
      iso_code: "KI",
    },
    {
      id: 120,
      name: "Kuwait",
      code: "KW",
      capital: "Kuwait City",
      region: "AS",
      language: {
        code: "ar",
        name: "Arabic",
      },
      flag: "https://restcountries.eu/data/kwt.svg",
      iso_code: "KW",
    },
    {
      id: 121,
      name: "Kyrgyzstan",
      code: "KG",
      capital: "Bishkek",
      region: "AS",
      language: {
        code: "ky",
        name: "Kyrgyz",
      },
      flag: "https://restcountries.eu/data/kgz.svg",
      iso_code: "KG",
    },
    {
      id: 122,
      name: "Lao People's Democratic Republic",
      code: "LA",
      capital: "Vientiane",
      region: "AS",
      language: {
        code: "lo",
        name: "Lao",
      },
      flag: "https://restcountries.eu/data/lao.svg",
      iso_code: "LA",
    },
    {
      id: 123,
      name: "Latvia",
      code: "LV",
      capital: "Riga",
      region: "EU",
      language: {
        code: "lv",
        name: "Latvian",
      },
      flag: "https://restcountries.eu/data/lva.svg",
      iso_code: "LV",
    },
    {
      id: 124,
      name: "Lebanon",
      code: "LB",
      capital: "Beirut",
      region: "AS",
      language: {
        code: "ar",
        name: "Arabic",
      },
      flag: "https://restcountries.eu/data/lbn.svg",
      iso_code: "LB",
    },
    {
      id: 125,
      name: "Lesotho",
      code: "LS",
      capital: "Maseru",
      region: "AF",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/lso.svg",
      iso_code: "LS",
    },
    {
      id: 126,
      name: "Liberia",
      code: "LR",
      capital: "Monrovia",
      region: "AF",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/lbr.svg",
      iso_code: "LR",
    },
    {
      id: 127,
      name: "Libya",
      code: "LY",
      capital: "Tripoli",
      region: "AF",
      language: {
        code: "ar",
        name: "Arabic",
      },
      flag: "https://restcountries.eu/data/lby.svg",
      iso_code: "LY",
    },
    {
      id: 128,
      name: "Liechtenstein",
      code: "LI",
      capital: "Vaduz",
      region: "EU",
      language: {
        code: "de",
        name: "German",
      },
      flag: "https://restcountries.eu/data/lie.svg",
      iso_code: "LI",
    },
    {
      id: 129,
      name: "Lithuania",
      code: "LT",
      capital: "Vilnius",
      region: "EU",
      language: {
        code: "lt",
        name: "Lithuanian",
      },
      flag: "https://restcountries.eu/data/ltu.svg",
      iso_code: "LT",
    },
    {
      id: 130,
      name: "Luxembourg",
      code: "LU",
      capital: "Luxembourg",
      region: "EU",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/lux.svg",
      iso_code: "LU",
    },
    {
      id: 131,
      name: "Macao",
      code: "MO",
      capital: "",
      region: "AS",
      language: {
        code: "zh",
        name: "Chinese",
      },
      flag: "https://restcountries.eu/data/mac.svg",
      iso_code: "MO",
    },
    {
      id: 132,
      name: "Macedonia (the former Yugoslav Republic of)",
      code: "MK",
      capital: "Skopje",
      region: "EU",
      language: {
        code: "mk",
        name: "Macedonian",
      },
      flag: "https://restcountries.eu/data/mkd.svg",
      iso_code: "MK",
    },
    {
      id: 133,
      name: "Madagascar",
      code: "MG",
      capital: "Antananarivo",
      region: "AF",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/mdg.svg",
      iso_code: "MG",
    },
    {
      id: 134,
      name: "Malawi",
      code: "MW",
      capital: "Lilongwe",
      region: "AF",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/mwi.svg",
      iso_code: "MW",
    },
    {
      id: 135,
      name: "Malaysia",
      code: "MY",
      capital: "Kuala Lumpur",
      region: "AS",
      language: {
        code: "",
        name: "Malaysian",
      },
      flag: "https://restcountries.eu/data/mys.svg",
      iso_code: "MY",
    },
    {
      id: 136,
      name: "Maldives",
      code: "MV",
      capital: "Malé",
      region: "AS",
      language: {
        code: "dv",
        name: "Divehi",
      },
      flag: "https://restcountries.eu/data/mdv.svg",
      iso_code: "MV",
    },
    {
      id: 137,
      name: "Mali",
      code: "ML",
      capital: "Bamako",
      region: "AF",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/mli.svg",
      iso_code: "ML",
    },
    {
      id: 138,
      name: "Malta",
      code: "MT",
      capital: "Valletta",
      region: "EU",
      language: {
        code: "mt",
        name: "Maltese",
      },
      flag: "https://restcountries.eu/data/mlt.svg",
      iso_code: "MT",
    },
    {
      id: 139,
      name: "Marshall Islands",
      code: "MH",
      capital: "Majuro",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/mhl.svg",
      iso_code: "MH",
    },
    {
      id: 140,
      name: "Martinique",
      code: "MQ",
      capital: "Fort-de-France",
      region: "Americas",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/mtq.svg",
      iso_code: "MQ",
    },
    {
      id: 141,
      name: "Mauritania",
      code: "MR",
      capital: "Nouakchott",
      region: "AF",
      language: {
        code: "ar",
        name: "Arabic",
      },
      flag: "https://restcountries.eu/data/mrt.svg",
      iso_code: "MR",
    },
    {
      id: 142,
      name: "Mauritius",
      code: "MU",
      capital: "Port Louis",
      region: "AF",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/mus.svg",
      iso_code: "MU",
    },
    {
      id: 143,
      name: "Mayotte",
      code: "YT",
      capital: "Mamoudzou",
      region: "AF",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/myt.svg",
      iso_code: "YT",
    },
    {
      id: 144,
      name: "Mexico",
      code: "MX",
      capital: "Mexico City",
      region: "NA",
      language: {
        code: "es",
        name: "Spanish",
      },
      flag: "https://restcountries.eu/data/mex.svg",
      iso_code: "MX",
    },
    {
      id: 145,
      name: "Micronesia (Federated States of)",
      code: "FM",
      capital: "Palikir",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/fsm.svg",
      iso_code: "FM",
    },
    {
      id: 146,
      name: "Moldova (Republic of)",
      code: "MD",
      capital: "Chișinău",
      region: "EU",
      language: {
        code: "ro",
        name: "Romanian",
      },
      flag: "https://restcountries.eu/data/mda.svg",
      iso_code: "MD",
    },
    {
      id: 147,
      name: "Monaco",
      code: "MC",
      capital: "Monaco",
      region: "EU",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/mco.svg",
      iso_code: "MC",
    },
    {
      id: 148,
      name: "Mongolia",
      code: "MN",
      capital: "Ulan Bator",
      region: "AS",
      language: {
        code: "mn",
        name: "Mongolian",
      },
      flag: "https://restcountries.eu/data/mng.svg",
      iso_code: "MN",
    },
    {
      id: 149,
      name: "Montenegro",
      code: "ME",
      capital: "Podgorica",
      region: "EU",
      language: {
        code: "sr",
        name: "Serbian",
      },
      flag: "https://restcountries.eu/data/mne.svg",
      iso_code: "ME",
    },
    {
      id: 150,
      name: "Montserrat",
      code: "MS",
      capital: "Plymouth",
      region: "NA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/msr.svg",
      iso_code: "MS",
    },
    {
      id: 151,
      name: "Morocco",
      code: "MA",
      capital: "Rabat",
      region: "AF",
      language: {
        code: "ar",
        name: "Arabic",
      },
      flag: "https://restcountries.eu/data/mar.svg",
      iso_code: "MA",
    },
    {
      id: 152,
      name: "Mozambique",
      code: "MZ",
      capital: "Maputo",
      region: "AF",
      language: {
        code: "pt",
        name: "Portuguese",
      },
      flag: "https://restcountries.eu/data/moz.svg",
      iso_code: "MZ",
    },
    {
      id: 153,
      name: "Myanmar",
      code: "MM",
      capital: "Naypyidaw",
      region: "AS",
      language: {
        code: "my",
        name: "Burmese",
      },
      flag: "https://restcountries.eu/data/mmr.svg",
      iso_code: "MM",
    },
    {
      id: 154,
      name: "Namibia",
      code: "NA",
      capital: "Windhoek",
      region: "AF",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/nam.svg",
      iso_code: "NA",
    },
    {
      id: 155,
      name: "Nauru",
      code: "NR",
      capital: "Yaren",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/nru.svg",
      iso_code: "NR",
    },
    {
      id: 156,
      name: "Nepal",
      code: "NP",
      capital: "Kathmandu",
      region: "AS",
      language: {
        code: "ne",
        name: "Nepali",
      },
      flag: "https://restcountries.eu/data/npl.svg",
      iso_code: "NP",
    },
    {
      id: 157,
      name: "Netherlands",
      code: "NL",
      capital: "Amsterdam",
      region: "EU",
      language: {
        code: "nl",
        name: "Dutch",
      },
      flag: "https://restcountries.eu/data/nld.svg",
      iso_code: "NL",
    },
    {
      id: 158,
      name: "New Caledonia",
      code: "NC",
      capital: "Nouméa",
      region: "OC",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/ncl.svg",
      iso_code: "NC",
    },
    {
      id: 159,
      name: "New Zealand",
      code: "NZ",
      capital: "Wellington",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/nzl.svg",
      iso_code: "NZ",
    },
    {
      id: 160,
      name: "Nicaragua",
      code: "NI",
      capital: "Managua",
      region: "NA",
      language: {
        code: "es",
        name: "Spanish",
      },
      flag: "https://restcountries.eu/data/nic.svg",
      iso_code: "NI",
    },
    {
      id: 161,
      name: "Niger",
      code: "NE",
      capital: "Niamey",
      region: "AF",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/ner.svg",
      iso_code: "NE",
    },
    {
      id: 162,
      name: "Nigeria",
      code: "NG",
      capital: "Abuja",
      region: "AF",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/nga.svg",
      iso_code: "NG",
    },
    {
      id: 163,
      name: "Niue",
      code: "NU",
      capital: "Alofi",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/niu.svg",
      iso_code: "NU",
    },
    {
      id: 164,
      name: "Norfolk Island",
      code: "NF",
      capital: "Kingston",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/nfk.svg",
      iso_code: "NF",
    },
    {
      id: 165,
      name: "Korea (Democratic People's Republic of)",
      code: "KP",
      capital: "Pyongyang",
      region: "AS",
      language: {
        code: "ko",
        name: "Korean",
      },
      flag: "https://restcountries.eu/data/prk.svg",
      iso_code: "KP",
    },
    {
      id: 166,
      name: "Northern Mariana Islands",
      code: "MP",
      capital: "Saipan",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/mnp.svg",
      iso_code: "MP",
    },
    {
      id: 167,
      name: "Norway",
      code: "NO",
      capital: "Oslo",
      region: "EU",
      language: {
        code: "no",
        name: "Norwegian",
      },
      flag: "https://restcountries.eu/data/nor.svg",
      iso_code: "NO",
    },
    {
      id: 168,
      name: "Oman",
      code: "OM",
      capital: "Muscat",
      region: "AS",
      language: {
        code: "ar",
        name: "Arabic",
      },
      flag: "https://restcountries.eu/data/omn.svg",
      iso_code: "OM",
    },
    {
      id: 169,
      name: "Pakistan",
      code: "PK",
      capital: "Islamabad",
      region: "AS",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/pak.svg",
      iso_code: "PK",
    },
    {
      id: 170,
      name: "Palau",
      code: "PW",
      capital: "Ngerulmud",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/plw.svg",
      iso_code: "PW",
    },
    {
      id: 171,
      name: "Palestine, State of",
      code: "PS",
      capital: "Ramallah",
      region: "AS",
      language: {
        code: "ar",
        name: "Arabic",
      },
      flag: "https://restcountries.eu/data/pse.svg",
      iso_code: "PS",
    },
    {
      id: 172,
      name: "Panama",
      code: "PA",
      capital: "Panama City",
      region: "NA",
      language: {
        code: "es",
        name: "Spanish",
      },
      flag: "https://restcountries.eu/data/pan.svg",
      iso_code: "PA",
    },
    {
      id: 173,
      name: "Papua New Guinea",
      code: "PG",
      capital: "Port Moresby",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/png.svg",
      iso_code: "PG",
    },
    {
      id: 174,
      name: "Paraguay",
      code: "PY",
      capital: "Asunción",
      region: "SA",
      language: {
        code: "es",
        name: "Spanish",
      },
      flag: "https://restcountries.eu/data/pry.svg",
      iso_code: "PY",
    },
    {
      id: 175,
      name: "Peru",
      code: "PE",
      capital: "Lima",
      region: "SA",
      language: {
        code: "es",
        name: "Spanish",
      },
      flag: "https://restcountries.eu/data/per.svg",
      iso_code: "PE",
    },
    {
      id: 176,
      name: "Philippines",
      code: "PH",
      capital: "Manila",
      region: "AS",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/phl.svg",
      iso_code: "PH",
    },
    {
      id: 177,
      name: "Pitcairn",
      code: "PN",
      capital: "Adamstown",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/pcn.svg",
      iso_code: "PN",
    },
    {
      id: 178,
      name: "Poland",
      code: "PL",
      capital: "Warsaw",
      region: "EU",
      language: {
        code: "pl",
        name: "Polish",
      },
      flag: "https://restcountries.eu/data/pol.svg",
      iso_code: "PL",
    },
    {
      id: 179,
      name: "Portugal",
      code: "PT",
      capital: "Lisbon",
      region: "EU",
      language: {
        code: "pt",
        name: "Portuguese",
      },
      flag: "https://restcountries.eu/data/prt.svg",
      iso_code: "PT",
    },
    {
      id: 180,
      name: "Puerto Rico",
      code: "PR",
      capital: "San Juan",
      region: "NA",
      language: {
        code: "es",
        name: "Spanish",
      },
      flag: "https://restcountries.eu/data/pri.svg",
      iso_code: "PR",
    },
    {
      id: 181,
      name: "Qatar",
      code: "QA",
      capital: "Doha",
      region: "AS",
      language: {
        code: "ar",
        name: "Arabic",
      },
      flag: "https://restcountries.eu/data/qat.svg",
      iso_code: "QA",
    },
    {
      id: 182,
      name: "Republic of Kosovo",
      code: "XK",
      capital: "Pristina",
      region: "EU",
      language: {
        code: "sq",
        name: "Albanian",
      },
      flag: "https://restcountries.eu/data/kos.svg",
      iso_code: "XK",
    },
    {
      id: 183,
      name: "Réunion",
      code: "RE",
      capital: "Saint-Denis",
      region: "AF",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/reu.svg",
      iso_code: "RE",
    },
    {
      id: 184,
      name: "Romania",
      code: "RO",
      capital: "Bucharest",
      region: "EU",
      language: {
        code: "ro",
        name: "Romanian",
      },
      flag: "https://restcountries.eu/data/rou.svg",
      iso_code: "RO",
    },
    {
      id: 185,
      name: "Russian Federation",
      code: "RU",
      capital: "Moscow",
      region: "EU",
      language: {
        code: "ru",
        name: "Russian",
      },
      flag: "https://restcountries.eu/data/rus.svg",
      iso_code: "RU",
    },
    {
      id: 186,
      name: "Rwanda",
      code: "RW",
      capital: "Kigali",
      region: "AF",
      language: {
        code: "rw",
        name: "Kinyarwanda",
      },
      flag: "https://restcountries.eu/data/rwa.svg",
      iso_code: "RW",
    },
    {
      id: 187,
      name: "Saint Barthélemy",
      code: "BL",
      capital: "Gustavia",
      region: "NA",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/blm.svg",
      iso_code: "BL",
    },
    {
      id: 188,
      name: "Saint Helena, Ascension and Tristan da Cunha",
      code: "SH",
      capital: "Jamestown",
      region: "AF",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/shn.svg",
      iso_code: "SH",
    },
    {
      id: 189,
      name: "Saint Kitts and Nevis",
      code: "KN",
      capital: "Basseterre",
      region: "NA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/kna.svg",
      iso_code: "KN",
    },
    {
      id: 190,
      name: "Saint Lucia",
      code: "LC",
      capital: "Castries",
      region: "NA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/lca.svg",
      iso_code: "LC",
    },
    {
      id: 191,
      name: "Saint Martin (French part)",
      code: "MF",
      capital: "Marigot",
      region: "NA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/maf.svg",
      iso_code: "MF",
    },
    {
      id: 192,
      name: "Saint Pierre and Miquelon",
      code: "PM",
      capital: "Saint-Pierre",
      region: "NA",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/spm.svg",
      iso_code: "PM",
    },
    {
      id: 193,
      name: "Saint Vincent and the Grenadines",
      code: "VC",
      capital: "Kingstown",
      region: "NA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/vct.svg",
      iso_code: "VC",
    },
    {
      id: 194,
      name: "Samoa",
      code: "WS",
      capital: "Apia",
      region: "OC",
      language: {
        code: "sm",
        name: "Samoan",
      },
      flag: "https://restcountries.eu/data/wsm.svg",
      iso_code: "WS",
    },
    {
      id: 195,
      name: "San Marino",
      code: "SM",
      capital: "City of San Marino",
      region: "EU",
      language: {
        code: "it",
        name: "Italian",
      },
      flag: "https://restcountries.eu/data/smr.svg",
      iso_code: "SM",
    },
    {
      id: 196,
      name: "Sao Tome and Principe",
      code: "ST",
      capital: "São Tomé",
      region: "AF",
      language: {
        code: "pt",
        name: "Portuguese",
      },
      flag: "https://restcountries.eu/data/stp.svg",
      iso_code: "ST",
    },
    {
      id: 197,
      name: "Saudi Arabia",
      code: "SA",
      capital: "Riyadh",
      region: "AS",
      language: {
        code: "ar",
        name: "Arabic",
      },
      flag: "https://restcountries.eu/data/sau.svg",
      iso_code: "SA",
    },
    {
      id: 198,
      name: "Senegal",
      code: "SN",
      capital: "Dakar",
      region: "AF",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/sen.svg",
      iso_code: "SN",
    },
    {
      id: 199,
      name: "Serbia",
      code: "RS",
      capital: "Belgrade",
      region: "EU",
      language: {
        code: "sr",
        name: "Serbian",
      },
      flag: "https://restcountries.eu/data/srb.svg",
      iso_code: "RS",
    },
    {
      id: 200,
      name: "Seychelles",
      code: "SC",
      capital: "Victoria",
      region: "AF",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/syc.svg",
      iso_code: "SC",
    },
    {
      id: 201,
      name: "Sierra Leone",
      code: "SL",
      capital: "Freetown",
      region: "AF",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/sle.svg",
      iso_code: "SL",
    },
    {
      id: 202,
      name: "Singapore",
      code: "SG",
      capital: "Singapore",
      region: "AS",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/sgp.svg",
      iso_code: "SG",
    },
    {
      id: 203,
      name: "Sint Maarten (Dutch part)",
      code: "SX",
      capital: "Philipsburg",
      region: "Americas",
      language: {
        code: "nl",
        name: "Dutch",
      },
      flag: "https://restcountries.eu/data/sxm.svg",
      iso_code: "SX",
    },
    {
      id: 204,
      name: "Slovakia",
      code: "SK",
      capital: "Bratislava",
      region: "EU",
      language: {
        code: "sk",
        name: "Slovak",
      },
      flag: "https://restcountries.eu/data/svk.svg",
      iso_code: "SK",
    },
    {
      id: 205,
      name: "Slovenia",
      code: "SI",
      capital: "Ljubljana",
      region: "EU",
      language: {
        code: "sl",
        name: "Slovene",
      },
      flag: "https://restcountries.eu/data/svn.svg",
      iso_code: "SI",
    },
    {
      id: 206,
      name: "Solomon Islands",
      code: "SB",
      capital: "Honiara",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/slb.svg",
      iso_code: "SB",
    },
    {
      id: 207,
      name: "Somalia",
      code: "SO",
      capital: "Mogadishu",
      region: "AF",
      language: {
        code: "ar",
        name: "Arabic",
      },
      flag: "https://restcountries.eu/data/som.svg",
      iso_code: "SO",
    },
    {
      id: 208,
      name: "South Africa",
      code: "ZA",
      capital: "Pretoria",
      region: "AF",
      language: {
        code: "en",
        iso639_2: "eng",
        name: "English",
        nativeName: "English",
      },
      flag: "https://restcountries.eu/data/zaf.svg",
      iso_code: "ZA",
    },
    {
      id: 209,
      name: "South Georgia and the South Sandwich Islands",
      code: "GS",
      capital: "King Edward Point",
      region: "NA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/sgs.svg",
      iso_code: "GS",
    },
    {
      id: 210,
      name: "Korea (Republic of)",
      code: "KR",
      capital: "Seoul",
      region: "AS",
      language: {
        code: "ko",
        name: "Korean",
      },
      flag: "https://restcountries.eu/data/kor.svg",
      iso_code: "KR",
    },
    {
      id: 211,
      name: "South Sudan",
      code: "SS",
      capital: "Juba",
      region: "AF",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/ssd.svg",
      iso_code: "SS",
    },
    {
      id: 212,
      name: "Spain",
      code: "ES",
      capital: "Madrid",
      region: "EU",
      language: {
        code: "es",
        name: "Spanish",
      },
      flag: "https://restcountries.eu/data/esp.svg",
      iso_code: "ES",
    },
    {
      id: 213,
      name: "Sri Lanka",
      code: "LK",
      capital: "Colombo",
      region: "AS",
      language: {
        code: "si",
        iso639_2: "sin",
        name: "Sinhalese",
        nativeName: "සිංහල",
      },
      flag: "https://restcountries.eu/data/lka.svg",
      iso_code: "LK",
    },
    {
      id: 214,
      name: "Sudan",
      code: "SD",
      capital: "Khartoum",
      region: "AF",
      language: {
        code: "ar",
        name: "Arabic",
      },
      flag: "https://restcountries.eu/data/sdn.svg",
      iso_code: "SD",
    },
    {
      id: 215,
      name: "Suriname",
      code: "SR",
      capital: "Paramaribo",
      region: "SA",
      language: {
        code: "nl",
        name: "Dutch",
      },
      flag: "https://restcountries.eu/data/sur.svg",
      iso_code: "SR",
    },
    {
      id: 216,
      name: "Svalbard and Jan Mayen",
      code: "SJ",
      capital: "Longyearbyen",
      region: "EU",
      language: {
        code: "no",
        name: "Norwegian",
      },
      flag: "https://restcountries.eu/data/sjm.svg",
      iso_code: "SJ",
    },
    {
      id: 217,
      name: "Swaziland",
      code: "SZ",
      capital: "Lobamba",
      region: "AF",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/swz.svg",
      iso_code: "SZ",
    },
    {
      id: 218,
      name: "Sweden",
      code: "SE",
      capital: "Stockholm",
      region: "EU",
      language: {
        code: "sv",
        name: "Swedish",
      },
      flag: "https://restcountries.eu/data/swe.svg",
      iso_code: "SE",
    },
    {
      id: 219,
      name: "Switzerland",
      code: "CH",
      capital: "Bern",
      region: "EU",
      language: {
        code: "de",
        name: "German",
      },
      flag: "https://restcountries.eu/data/che.svg",
      iso_code: "CH",
    },
    {
      id: 220,
      name: "Syrian Arab Republic",
      code: "SY",
      capital: "Damascus",
      region: "AS",
      language: {
        code: "ar",
        name: "Arabic",
      },
      flag: "https://restcountries.eu/data/syr.svg",
      iso_code: "SY",
    },
    {
      id: 221,
      name: "Taiwan",
      code: "TW",
      capital: "Taipei",
      region: "AS",
      language: {
        code: "zh",
        name: "Chinese",
      },
      flag: "https://restcountries.eu/data/twn.svg",
      iso_code: "TW",
    },
    {
      id: 222,
      name: "Tajikistan",
      code: "TJ",
      capital: "Dushanbe",
      region: "AS",
      language: {
        code: "tg",
        name: "Tajik",
      },
      flag: "https://restcountries.eu/data/tjk.svg",
      iso_code: "TJ",
    },
    {
      id: 223,
      name: "Tanzania, United Republic of",
      code: "TZ",
      capital: "Dodoma",
      region: "AF",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/tza.svg",
      iso_code: "TZ",
    },
    {
      id: 224,
      name: "Thailand",
      code: "TH",
      capital: "Bangkok",
      region: "AS",
      language: {
        code: "th",
        name: "Thai",
      },
      flag: "https://restcountries.eu/data/tha.svg",
      iso_code: "TH",
    },
    {
      id: 225,
      name: "Timor-Leste",
      code: "TL",
      capital: "Dili",
      region: "AS",
      language: {
        code: "pt",
        name: "Portuguese",
      },
      flag: "https://restcountries.eu/data/tls.svg",
      iso_code: "TL",
    },
    {
      id: 226,
      name: "Togo",
      code: "TG",
      capital: "Lomé",
      region: "AF",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/tgo.svg",
      iso_code: "TG",
    },
    {
      id: 227,
      name: "Tokelau",
      code: "TK",
      capital: "Fakaofo",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/tkl.svg",
      iso_code: "TK",
    },
    {
      id: 228,
      name: "Tonga",
      code: "TO",
      capital: "Nuku'alofa",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/ton.svg",
      iso_code: "TO",
    },
    {
      id: 229,
      name: "Trinidad and Tobago",
      code: "TT",
      capital: "Port of Spain",
      region: "SA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/tto.svg",
      iso_code: "TT",
    },
    {
      id: 230,
      name: "Tunisia",
      code: "TN",
      capital: "Tunis",
      region: "AF",
      language: {
        code: "ar",
        name: "Arabic",
      },
      flag: "https://restcountries.eu/data/tun.svg",
      iso_code: "TN",
    },
    {
      id: 231,
      name: "Turkey",
      code: "TR",
      capital: "Ankara",
      region: "AS",
      language: {
        code: "tr",
        name: "Turkish",
      },
      flag: "https://restcountries.eu/data/tur.svg",
      iso_code: "TR",
    },
    {
      id: 232,
      name: "Turkmenistan",
      code: "TM",
      capital: "Ashgabat",
      region: "AS",
      language: {
        code: "tk",
        name: "Turkmen",
      },
      flag: "https://restcountries.eu/data/tkm.svg",
      iso_code: "TM",
    },
    {
      id: 233,
      name: "Turks and Caicos Islands",
      code: "TC",
      capital: "Cockburn Town",
      region: "NA",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/tca.svg",
      iso_code: "TC",
    },
    {
      id: 234,
      name: "Tuvalu",
      code: "TV",
      capital: "Funafuti",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/tuv.svg",
      iso_code: "TV",
    },
    {
      id: 235,
      name: "Uganda",
      code: "UG",
      capital: "Kampala",
      region: "AF",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/uga.svg",
      iso_code: "UG",
    },
    {
      id: 236,
      name: "Ukraine",
      code: "UA",
      capital: "Kiev",
      region: "EU",
      language: {
        code: "uk",
        name: "Ukrainian",
      },
      flag: "https://restcountries.eu/data/ukr.svg",
      iso_code: "UA",
    },
    {
      id: 237,
      name: "United Arab Emirates",
      code: "AE",
      capital: "Abu Dhabi",
      region: "AS",
      language: {
        code: "ar",
        name: "Arabic",
      },
      flag: "https://restcountries.eu/data/are.svg",
      iso_code: "AE",
    },
    {
      id: 238,
      name: "United Kingdom of Great Britain and Northern Ireland",
      code: "GB",
      capital: "London",
      region: "EU",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/gbr.svg",
      iso_code: "GB",
    },
    {
      id: 239,
      name: "United States of America",
      code: "US",
      capital: "Washington, D.C.",
      region: "NA",
      language: {
        code: "en",
        iso639_2: "eng",
        name: "English",
        nativeName: "English",
      },
      flag: "https://restcountries.eu/data/usa.svg",
      iso_code: "US",
    },
    {
      id: 240,
      name: "Uruguay",
      code: "UY",
      capital: "Montevideo",
      region: "SA",
      language: {
        code: "es",
        name: "Spanish",
      },
      flag: "https://restcountries.eu/data/ury.svg",
      iso_code: "UY",
    },
    {
      id: 241,
      name: "Uzbekistan",
      code: "UZ",
      capital: "Tashkent",
      region: "AS",
      language: {
        code: "uz",
        name: "Uzbek",
      },
      flag: "https://restcountries.eu/data/uzb.svg",
      iso_code: "UZ",
    },
    {
      id: 242,
      name: "Vanuatu",
      code: "VU",
      capital: "Port Vila",
      region: "OC",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/vut.svg",
      iso_code: "VU",
    },
    {
      id: 243,
      name: "Venezuela (Bolivarian Republic of)",
      code: "VE",
      capital: "Caracas",
      region: "SA",
      language: {
        code: "es",
        name: "Spanish",
      },
      flag: "https://restcountries.eu/data/ven.svg",
      iso_code: "VE",
    },
    {
      id: 244,
      name: "Viet Nam",
      code: "VN",
      capital: "Hanoi",
      region: "AS",
      language: {
        code: "vi",
        name: "Vietnamese",
      },
      flag: "https://restcountries.eu/data/vnm.svg",
      iso_code: "VN",
    },
    {
      id: 245,
      name: "Wallis and Futuna",
      code: "WF",
      capital: "Mata-Utu",
      region: "OC",
      language: {
        code: "fr",
        name: "French",
      },
      flag: "https://restcountries.eu/data/wlf.svg",
      iso_code: "WF",
    },
    {
      id: 246,
      name: "Western Sahara",
      code: "EH",
      capital: "El Aaiún",
      region: "AF",
      language: {
        code: "es",
        name: "Spanish",
      },
      flag: "https://restcountries.eu/data/esh.svg",
      iso_code: "EH",
    },
    {
      id: 247,
      name: "Yemen",
      code: "YE",
      capital: "Sana'a",
      region: "AS",
      language: {
        code: "ar",
        name: "Arabic",
      },
      flag: "https://restcountries.eu/data/yem.svg",
      iso_code: "YE",
    },
    {
      id: 248,
      name: "Zambia",
      code: "ZM",
      capital: "Lusaka",
      region: "AF",
      language: {
        code: "en",
        name: "English",
      },
      flag: "https://restcountries.eu/data/zmb.svg",
      iso_code: "ZM",
    },
    {
      id: 249,
      name: "Zimbabwe",
      code: "ZW",
      capital: "Harare",
      region: "AF",
      language: {
        code: "en",
        iso639_2: "eng",
        name: "English",
        nativeName: "English",
      },
      flag: "https://restcountries.eu/data/zwe.svg",
      iso_code: "ZW",
    },
  ]);
}
